### ISSUE TITLE
bug: overlap on carriers

### ISSUE THREAD

**Issue by GavPierce** [GavPierce/Cosmic-Odyssey#26]
Currently if two or more carriers are on the same location, you only see the amount of 1 of them. 
They should combine the total.

**Comment by JaredTheHammer** [comment]
What if two or more carriers are overlapping? We have another icon that represents a fleet/armada to show there is more than one carrier, and this icon is a little larger. This would help people to click and identify all the carriers in the stack for more info instead of assuming there is only one carrier.

I also think as we shift away from carriers being just transport hubs for little ships and them having their own values and additional costs then it will be less likely to have a bunch of carriers/capital ships stacked. We still need a way to identify easily if there is more than one but it should be far less common and the building, protecting and destroying of carriers/capital ships should be more significant than just the loss of 25 credits.

**Comment by JaredTheHammer** [comment]
![image](https://github.com/GavPierce/Cosmic-Odyssey/assets/11431019/e4cdfd43-5dc0-4ef7-bb4e-9abcdd8fb84d)

**Comment by JaredTheHammer** [comment]
We need a symmetrical SVG to abstractly represent any group of ships.

**Comment by JaredTheHammer** [comment]
![image](https://github.com/GavPierce/Cosmic-Odyssey/assets/11431019/1a1a73b9-680c-4bb5-8510-428f015d5d40)

**Comment by JaredTheHammer** [comment]
![image](https://github.com/GavPierce/Cosmic-Odyssey/assets/11431019/f3e3d1e5-6e77-4602-9e68-3501857a0792)

**Comment by JaredTheHammer** [comment]
![image](https://github.com/GavPierce/Cosmic-Odyssey/assets/11431019/0fab5889-50f1-49de-aeab-e26222cb01aa)

**Comment by JaredTheHammer** [comment]
Any of these would have my vote but I like the topmost one I first posted.
Which one do you like Gavin?
@GavPierce

**Comment by JaredTheHammer** [comment]
You fix this.

**Comment by JaredTheHammer** [comment]
@GavPierce  

Found a graphical bug related to carriers stacking.

It is an infiltrator and lieutenant. I'm on my PC.


I refreshed the browser and it still occured.


![Image](https://github.com/GavPierce/Cosmic-Odyssey/assets/11431019/672089d6-2faf-45d1-ac33-bfd50f12284c)




![Image](https://github.com/GavPierce/Cosmic-Odyssey/assets/11431019/361a53a8-036f-46a0-bba1-a1f1c4351bb5)

**Comment by JaredTheHammer** [comment]
At the same time it does work for some carriers that are stacked.



![Image](https://github.com/GavPierce/Cosmic-Odyssey/assets/11431019/672729f7-d673-4a6a-a80f-edb1cfbebc38)
